# Generated by Django 5.2.6 on 2025-10-08 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0003_enquiry_product_enquiry_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry',
            name='service',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
