# Generated by Django 5.2.6 on 2025-10-08 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0004_alter_enquiry_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='phone',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
