# Generated by Django 5.2.6 on 2025-11-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0005_enquiry_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='destination',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='service',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
